version: '3.8'
services:
    app-db:
        image: mongo:latest
        container_name: app-db
        restart: unless-stopped
        command: mongod
        environment:
            MONGO_INITDB_DATABASE: ${DB_NAME}
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        ports:
            - 27017:27017
    app:
        image: app
        container_name: app
        depends_on:
            - app-db
        ports:
            - ${PORT}:${PORT}
volumes:
    mongodbdata:
